services:
  # frontend-prod:
  #   depends_on:
  #     - anvil
  #   build:
  #     context: ./ui/debug
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000

  frontend-debug:
    depends_on:
      - anvil
    build:
      context: ./ui/debug
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  anvil:
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.anvil
    ports:
      - 8545:8545

  deploy:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.deploy